/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        surface: 'var(--surface)',
        'surface-elevated': 'var(--surface-elevated)',
        foreground: 'var(--foreground)',
        muted: 'var(--muted-foreground)',
        primary: {
          DEFAULT: 'var(--primary)',
          hover: 'var(--primary-hover)',
          foreground: 'var(--primary-foreground)',
        },
        border: 'var(--border)',
        ring: 'var(--ring)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        danger: 'var(--danger)',
        'accent-blue': 'var(--accent-blue)',
        'accent-pink': 'var(--accent-pink)',
        'accent-teal': 'var(--accent-teal)',
        'accent-purple': 'var(--accent-purple)',
        'accent-mist': 'var(--accent-mist)',
        'accent-sage': 'var(--accent-sage)',
        'accent-lavender': 'var(--accent-lavender)',
        'accent-deep-blue': 'var(--accent-deep-blue)',
        cosmic: 'var(--primary)',
        gtm: {
          bg: 'var(--background)',
          card: 'var(--surface-elevated)',
          accent: 'var(--primary)',
          border: 'var(--border)',
        },
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
      },
      maxWidth: {
        'container-app': 'var(--container-app)',
        'container-marketing': 'var(--container-marketing)',
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          'SF Pro Text',
          'SF Pro Display',
          'system-ui',
          'sans-serif',
        ],
        display: [
          '-apple-system',
          'BlinkMacSystemFont',
          'SF Pro Display',
          'SF Pro Text',
          'system-ui',
          'sans-serif',
        ],
        mono: ['SF Mono', 'ui-monospace', 'Menlo', 'Monaco', 'monospace'],
      },
      fontSize: {
        // Trims Tailwind's default numeric scale to Apple/SF density.
        xs: ['0.6875rem', { lineHeight: '1rem' }],
        sm: ['0.8125rem', { lineHeight: '1.2rem' }],
        base: ['0.9375rem', { lineHeight: '1.45rem' }],
        lg: ['1.0625rem', { lineHeight: '1.6rem' }],
        xl: ['1.1875rem', { lineHeight: '1.65rem' }],
        '2xl': ['1.375rem', { lineHeight: '1.75rem' }],
        '3xl': ['1.625rem', { lineHeight: '1.9rem' }],
        '4xl': ['1.875rem', { lineHeight: '2.1rem' }],
        '5xl': ['2.25rem', { lineHeight: '1' }],
        '6xl': ['2.75rem', { lineHeight: '1' }],
        'body-sm': ['var(--font-size-sm)', { lineHeight: 'var(--leading-normal)' }],
        body: ['var(--font-size-base)', { lineHeight: 'var(--leading-relaxed)' }],
        'body-lg': ['var(--font-size-lg)', { lineHeight: 'var(--leading-relaxed)' }],
        title: ['var(--font-size-xl)', { lineHeight: 'var(--leading-tight)' }],
        'page-title': ['var(--font-size-3xl)', { lineHeight: 'var(--leading-tight)' }],
        tile: 'var(--font-size-tile)',
        display: ['var(--font-size-display)', { lineHeight: 'var(--leading-tight)' }],
        'stat-value': ['var(--font-size-2xl)', { lineHeight: 'var(--leading-tight)' }],
      },
      lineHeight: {
        tight: 'var(--leading-tight)',
        normal: 'var(--leading-normal)',
        relaxed: 'var(--leading-relaxed)',
      },
      letterSpacing: {
        eyebrow: 'var(--tracking-eyebrow)',
      },
    },
  },
  plugins: [],
};
