{{- if .Values.license.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aurora.fullname" . }}-license
  labels:
    {{- include "aurora.labels" . | nindent 4 }}
type: Opaque
stringData:
  license.key: {{ .Values.license.key | quote }}
{{- end }}
