apiVersion: v1
kind: Service
metadata:
  name: {{ include "aurora.fullname" . }}-api
  labels:
    {{- include "aurora.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      name: http
  selector:
    {{- include "aurora.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aurora.fullname" . }}-web
  labels:
    {{- include "aurora.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      name: http
  selector:
    {{- include "aurora.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
